version: '3.8'

services:
  expo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streetpaws-expo
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    command: npm start
